baseURL = "https://newnaos.netlify.app"
languageCode = "fr-be"
title = "Naos Atelier"
disableKinds = ["taxonomy", "term", "RSS"]
removePathAccents = true
defaultContentLanguage = 'fr'

[params]
    author = "Robin Foguenne | Studio Colibri"
    cloudinary_url = "https://res.cloudinary.com/naos/image/upload/"
