baseURL = "https://www.naos-atelier.be/"
languageCode = "fr-be"
title = "Naos Atelier"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
removePathAccents = true
defaultContentLanguage = 'fr'

[params]
    author = "Robin Foguenne | Studio Colibri"
    cloudinary_url = "https://res.cloudinary.com/naos/image/upload/"
