backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://www.naos-atelier.be
display_url: https://www.naos-atelier.be
logo_url: https://www.naos-atelier.be/assets/img/naos-atelier-logo.svg

locale: 'fr'

show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

media_library:
  name: cloudinary
  config:
    cloud_name: naos
    api_key: 574487421299888
    output_filename_only: true

collections:
  - name: "commerces"
    label: "Commerces" 
    folder: "content/realisations/commerces" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "commerces"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "cuisines"
    label: "Cuisines" 
    folder: "content/realisations/cuisines" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "cuisines"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  
  - name: "espaces-professionnels"
    label: "Espaces professionnels" 
    folder: "content/realisations/espaces-professionnels" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "espaces-professionnels"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  
  - name: "publics"
    label: "Espaces publics" 
    folder: "content/realisations/publics" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "publics"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  
  - name: "salles-de-bain"
    label: "Salles de bain" 
    folder: "content/realisations/salles-de-bain" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "salles-de-bain"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  
  - name: "sejours"
    label: "Séjours" 
    folder: "content/realisations/sejours" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "sejours"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  
  - name: "tables"
    label: "Tables" 
    folder: "content/realisations/tables" 
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "categories", name: "categories", widget: "hidden", default: "tables"}
      - {label: "Titre", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        format: "YYYY-MM-DD"
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: false
      - label: "Galerie d'images"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        label_singular: "Image"
        field: {label: Image, name: image, widget: image}
      - {label: "Contenu", name: "body", widget: "markdown"}  